apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kartero.fullname" . }}-allowlist
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kartero.labels" . | nindent 4 }}
data:
  allowlist.yaml: |
{{ .Files.Get "allowlist.yaml" | indent 4 }}
