apiVersion: v2
name: kartero
description: Pulls OTLP JSON from CI artifacts and delivers it to an OTLP/HTTP backend
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - rust
  - otlp
  - ci
  - telemetry
home: https://github.com/kunobi-ninja/kartero
sources:
  - https://github.com/kunobi-ninja/kartero
maintainers:
  - name: Zondax
    url: https://zondax.ch
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: kartero
      image: docker.io/zondax/kartero:v0.2.0
